### ISSUE TITLE
Tabs in gerneral

### ISSUE THREAD

**Issue by hone-zaun** [sajidali007522/edu#6]
1. The Tabs should not be solved with JavaScript! There are some simple pure CSS rules to achieve that.
2. These Tabs should use the whole space on mobile and tablet.
    * ![grafik](https://user-images.githubusercontent.com/51439140/76219748-99f51600-6216-11ea-9e1e-b29103b1378c.png)
3. We need to change the look and feel on mobiles even further. We can't use a scrollbar on the bottom of the tabs here. Please make them multiline if we ran out of space!
    * ![grafik](https://user-images.githubusercontent.com/51439140/76219938-e80a1980-6216-11ea-8aac-314936da9e6b.png)
    * Take a look here: https://github.com/jgthms/bulma/issues/1344#issuecomment-583452885

**Comment by sajidali007522** [comment]
I agree with you first screenshot above like 4 tabs need to cover and will fix this issue, 
but for mobile version not have designer choice, I will talk to him and see what he agree about it.

**Comment by sajidali007522** [comment]
and for second mobile scrollbar, we are using bulma design, 
In start i try to make some adjustment but you know i restricted for custom work. 
Now if I done some work then must need to do custom.

**Comment by hone-zaun** [comment]
@sajidali007522 Yeah, that's right. Bulma also uses scrollbars for the tabs. That's why I posted a link to a possibly quick solution from bulmas own repository.

And actually something like this would do the trick for now:

```css
@media screen and (max-width: 768px)  {
    .tabs.is-multiline ul {
	flex-shrink: 1;
	flex-wrap: wrap;
    }
    .tabs.is-multiline li {
        margin-bottom: .75rem;
    }
}
```

![grafik](https://user-images.githubusercontent.com/51439140/76261397-2d036f80-625a-11ea-9553-e641476d870b.png)
